### ISSUE TITLE
region & geometry selection

### ISSUE THREAD

**Issue by sewnie** [alpheratz0/xscreenshot#1]
pretty straight forward i suppose.

this can be used along with xdotool like so:
```
~ $ xdotool selectwindow getwindowgeometry 
Window 10485782
  Position: 671,0 (screen: 0)
  Geometry: 1245x1057
~ $ 
```

**Comment by alpheratz0** [comment]
Hi @wael444, sorry, but I don't get what you mean

**Comment by sewnie** [comment]
https://user-images.githubusercontent.com/47404953/206863266-5315a90d-cbf7-4462-a699-4cae3b74607b.mp4

**Comment by alpheratz0** [comment]
Something like this?

```sh
#!/bin/sh -e

geom=$(slop)
root=$(xhsr)
spath=$(xscreenshot -p -w "$root")
pngcrop -i "$spath" -o "$spath" "$geom"

if test "$1" = "-o" -a -n "$2"; then
	mv "$spath" "$2"
fi
```

**Comment by sewnie** [comment]
so, that script gets a region, makes a temporary file with the full screen and just crop it? well yeah that is what i meant but without the need of something like `xhsr` or `slop`.

**Comment by alpheratz0** [comment]
> so, that script gets a region, makes a temporary file with the full screen and just crop it? well yeah that is what i meant but without the need of something like `xhsr` or `slop`.

You want xscreenshot to do what slop does? That's against modularity :(

**Comment by sewnie** [comment]
> You want xscreenshot to do what slop does? That's against modularity :(

yeah sorry! i suggesed a `slop` simple ~~suckless~~ alternative instead.

i unfortunately don't know how to program in C how to interacte with X (only thing i did was list Xinerama screens), so it's okay if you don't want to try to make this.

**Comment by alpheratz0** [comment]
>yeah sorry! i suggesed a slop simple suckless alternative instead.

As a standalone utility yes, as incorporated within xscreenshot source no.

>i unfortunately don't know how to program in C how to interacte with X (only thing i did was list Xinerama screens), so it's okay if you don't want to try to make this.

Yeah I will give it a try, I need to learn colormaps, transparency stuff to make the rectangle border opaque but the inside full transparent, added it to the list of projects to do!

**Comment by sewnie** [comment]
@alpheratz0 , are you sure having to get the entire xorg screen, and crop it to the region selected is efficient?

**Comment by alpheratz0** [comment]
> @alpheratz0 , are you sure having to get the entire xorg screen, and crop it to the region selected is efficient?

Well, it's such a minimal difference in terms of efficiency that I wouldn't sacrifice code simplicity for it.
